name: run android tests in Github runner

on: push

jobs: 
  run-mobile-tests:
    runs-on: macos-latest

    steps:
      - name: pull the proejct into the runner
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Install UIAutomator2
        run: npm install appium-uiautomator2-driver

      - name: setup appium
        run: |
          npm install -g appium@next
          appium -v
          appium &>/dev/null &

      - name: run appium android tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          script: npm run android