name: run android tests in Github runner

on: push

jobs: 
  run-mobile-tests:
    runs-on: macos-latest

    steps:
      - name: Change timezone
        uses: sudo ln -sf /usr/share/zoneinfo/Africa/Johannesburg /etc/localtime

      - name: pull the project into the runner
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: setup appium
        run: |
          npm install -g appium@next
          
      - name: Check appium version
        run: appium -v

      - name: Install UIAutomator2 and run Appium
        run: |
          appium driver install uiautomator2
          appium driver list --installed
          appium -a 127.0.0.1 -p 4723 &>/dev/null &
          
      - name: run appium android tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: google_apis
          arch: x86_64
          script: npm run android